version: '3'
services:

  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - app
  app:
    container_name: react
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
